### ISSUE TITLE
Add Benchmark?

### ISSUE THREAD

**Issue by SleepBook** [tcp-acceleration-service/tas#1]
Is it possible to add the benchmarks into the repo as well? Thanks

**Comment by FreakyPenguin** [comment]
We have the benchmarks in a separate repo here: https://github.com/tcp-acceleration-service/benchmarks
Is that what you're looking for? Or is something missing? There are quite a few non-TAS specific things in there so we chose to keep those in a separate repo.

**Comment by FreakyPenguin** [comment]
I'll close this, happy to re-open if something is still missing.

**Comment by SleepBook** [comment]
Thanks :-) that's what I am looking for
