### ISSUE TITLE
Assertion failure in uxsocket_receive

### ISSUE THREAD

**Issue by ash995** [tcp-acceleration-service/tas#11]
The following assertion inside the uxsocket_receive function fails

`assert(cmsg->cmsg_len == CMSG_LEN(sizeof(int)));`

cmsg->cmsg_len is set to 8, whereas CMSG_LEN(sizeof(int)) returns 20.
Any idea as to why this may be happening?

**Comment by FreakyPenguin** [comment]
Sorry for the delay. Off the top of my head I don't have an idea why this might happen. Is anything else going wrong before that? What are you doing to trigger this?

The message received there is sent from `flextcp_kernel_newctx` in `lib/tas/kernel.c`. So as a first step I would check the control message size there. Also check the `.msg_controllen` fields on both ends.

**Comment by ash995** [comment]
Hello Antione. The message at uxsocket_receive seems to coming from some other place because flextcp_kernel_newctx is never invoked. I put a print statement at the beginning of flextcp_kernel_newctx, and that line never prints.

**Comment by ash995** [comment]
Value of .msg_controllen field on both sides is 24.
cmsg->cmsg_len right before sending is 20, but when it's received the value of cmsg->cmsg_len changes to 24.

**Comment by ash995** [comment]
The recvmsg before the assertion fails as well, and returns -1. The cause of the failure is "Bad Address".

**Comment by FreakyPenguin** [comment]
Ah that would at least explain the unexpected values of `cmsg_len`. Not quite sure where the bad address for `recvmsg` would be coming from. Maybe set a breakpoint there and have a look at what pointers might be bad there (just looking at the code I really don't see anything...). Or maybe strace would also show this.

(I'll commit a fix to check the `recvmsg` result before checking the control data to avoid the initial confusion)

**Comment by ash995** [comment]
req_rx was not getting initialized to 0 for some reason and was getting initialized by some garbage value. As soon as I set the value of req_rx to 0 while setting up struct application, the issue was fixed.
