### ISSUE TITLE
Using 1G huge pages instead of 2M

### ISSUE THREAD

**Issue by sarsanaee** [tcp-acceleration-service/tas#4]
Hello,

I would like to use 1G huge pages instead of using 2M huge pages that are described in the documentation.

There is a function called `shm_preinit` which tries to grab some pages before DPDK does anything. I'm wondering why it doesn't work with 1G page size, however, it works properly with the 2M page size.

I run this command `sudo tas/tas --ip-addr=10.0.0.1/24 --fp-cores-max=1` and get the following error:

```
util_create_shmsiszed: ftruncate failed: Invalid argument
mapping flexnic internal memory failed
```

Has it designed to work with the 2M page sizes? It doesn't make sense to me though. Is there anything I'm missing?

Thanks,
Alireza

**Comment by FreakyPenguin** [comment]
Hi Alireza,

It's been a few refactors ago that I last tried using 1G pages, so not exactly sure what's going on here. But my guess based on the error message would be this:

TAS creates multiple shared memory regions, not all of which are large enough for 1GB pages. Off the top of my head, there is one region for data exchange with applications, this is the larger one and a small one (I think 32Mb by default?) for flow state.

Not exactly sure how linux reacts if you try to create a shm region of a size that's not a multiple of 1GB. A simple thing to try would be to just round up the size in the code to see if that fixes the problem.

Hope this helps,
Antoine

**Comment by sarsanaee** [comment]
Hi Antoine,

This helped:

> Not exactly sure how linux reacts if you try to create a shm region of a size that's not a multiple of 1GB. A simple thing to try would be to just round up the size in the code to see if that fixes the problem.

As you said, the problem was with the `#define FLEXNIC_INTERNAL_MEM_SIZE (1024 * 1024 * 32)`. I just changed it to `1024 * 1024 * 1024` and now it works properly.

Thanks,
Alireza
